# Generated by Django 2.2.7 on 2020-01-05 01:04

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('image', models.CharField(max_length=32)),
                ('slug', models.SlugField(max_length=32, verbose_name='Nombre slug')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=18, null=True, verbose_name='Teléfono')),
                ('avatar', models.ImageField(default='avatar/default.png', upload_to=authentication.models.user_directory_path)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to=authentication.models.cover_photo_directory_path)),
                ('map', models.URLField(blank=True, max_length=250, null=True)),
                ('terms_conditions', models.BooleanField(default=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Commune')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
